apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-psql
  labels:
    app: {{ .Release.Name }}-psql
spec:
  replicas: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}-psql
  template:
    metadata:
      name: {{ .Release.Name }}-psql
      labels:
        app: {{ .Release.Name }}-psql
    spec:
      imagePullSecrets:
        - name: regcred
      {{- if .Values.appNodeSelector }}
      nodeSelector:
        {{- toYaml .Values.appNodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations.appNodeTolerations }}
      tolerations:
        {{- toYaml .Values.tolerations.appNodeTolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-psql
          image: "{{ tpl .Values.postgres.image.imageUrl . }}:{{ .Values.postgres.image.imageTag }}"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              sleep infinity
          {{- if not .Values.postgres.enabled }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: qualytics-creds
                  key: connection_url
          {{- end }}
          {{- if .Values.postgres.enabled }}
          volumeMounts:
            - name: postgres-snapshots-pvc
              mountPath: /mnt/postgres/data
          {{- end }}
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 200Mi
      restartPolicy: Always
      {{- if .Values.postgres.enabled }}
      volumes:
        - name: postgres-snapshots-pvc
          persistentVolumeClaim:
            claimName: postgres-snapshots-claim
      {{- end }}